#' Get Chi PPV Parameters and Save Parameter Data Frame
#'
#' This function generates the Beta distribution parameters for the positive predictive
#' value (PPV) of the cholera clinical case definition under endemic and epidemic
#' conditions (chi_endemic and chi_epidemic) and saves them as a parameter data frame.
#'
#' Estimates are manually extracted from Weins et al. 2023 (PLOS Medicine,
#' doi:10.1371/journal.pmed.1004286), which characterises the cholera surveillance
#' pyramid across sub-Saharan African settings.
#'
#' @param PATHS A list containing paths where the parameter data will be saved.
#'   Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{MODEL_INPUT}: Path to the directory where the parameter data frame will be saved.
#' }
#' @return A data frame containing the Beta distribution parameters for chi_endemic
#'   (low/all-settings estimate) and chi_epidemic (high/outbreak estimate).
#' @export

get_suspected_cases <- function(PATHS) {

     # Estimates manually extracted from Weins et al 2023: https://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1004286
     # "Proportion of suspected cases that are true infections" = PPV = chi

     # chi_endemic: Low estimate (all settings) - endemic/inter-outbreak periods
     probs_all <- c(0.24, 0.52, 0.8)
     prm_all <- propvacc::get_beta_params(quantiles = c(0.0275, 0.5, 0.975),
                                          probs = probs_all)

     # chi_epidemic: High estimate (during outbreaks) - epidemic periods
     probs_outbreak <- c(0.40, 0.78, 0.99)
     prm_outbreak <- propvacc::get_beta_params(quantiles = c(0.0275, 0.5, 0.975),
                                               probs = probs_outbreak)

     # Create a parameter data frame with the distribution parameters

     param_df_point <-
          make_param_df(
          variable_name = "chi",
          variable_description = c("PPV among suspected cases (chi_endemic): Point estimate low (all settings)",
                                   "PPV among suspected cases (chi_epidemic): Point estimate high (during outbreaks)"),
          parameter_distribution = "beta",
          parameter_name = c("mean", "mean"),
          parameter_value = c(probs_all[2], probs_outbreak[2])
     )

     param_df_stoch <-
          make_param_df(
          variable_name = "chi",
          variable_description = c("PPV among suspected cases (chi_endemic): Low estimate (all settings)",
                                   "PPV among suspected cases (chi_endemic): Low estimate (all settings)",
                                   "PPV among suspected cases (chi_epidemic): High estimate (during outbreaks)",
                                   "PPV among suspected cases (chi_epidemic): High estimate (during outbreaks)"),
          parameter_distribution = "beta",
          parameter_name = c("shape1", "shape2", "shape1", "shape2"),
          parameter_value = c(prm_all$shape1, prm_all$shape2, prm_outbreak$shape1, prm_outbreak$shape2)
     )


     param_df <- rbind(param_df_point, param_df_stoch)

     # Save the parameter data frame
     param_path <- file.path(PATHS$MODEL_INPUT, "param_chi_suspected_cases.csv")
     utils::write.csv(param_df, param_path, row.names = FALSE)
     message(paste("Parameter data frame for chi (PPV) saved to:", param_path))

}
