#' Plot Chi PPV Prior Distributions
#'
#' This function loads the parameter data frame for the positive predictive value (PPV)
#' of the cholera clinical case definition from the `param_chi_suspected_cases.csv` file
#' and generates a plot showing the Beta prior distributions for chi_endemic (low/all-settings
#' estimate) and chi_epidemic (high/outbreak estimate).
#'
#' @param PATHS A list containing paths where the parameter data and figures will be saved. Typically generated by the `get_paths()` function and should include:
#' \itemize{
#'   \item \strong{MODEL_INPUT}: Path to the directory where the parameter data frame is stored.
#'   \item \strong{DOCS_FIGURES}: Path to the directory where the plot will be saved.
#' }
#' @export

plot_suspected_cases <- function(PATHS) {

     # Load the parameter data frame
     param_path <- file.path(PATHS$MODEL_INPUT, "param_chi_suspected_cases.csv")
     param_df <- utils::read.csv(param_path, stringsAsFactors = FALSE)
     message(paste("Parameter data loaded from:", param_path))

     # Extract parameters for chi_endemic (low/all-settings) and chi_epidemic (high/outbreak)
     shape1_all <- param_df$parameter_value[param_df$variable_description == "PPV among suspected cases (chi_endemic): Low estimate (all settings)" & param_df$parameter_name == "shape1"]
     shape2_all <- param_df$parameter_value[param_df$variable_description == "PPV among suspected cases (chi_endemic): Low estimate (all settings)" & param_df$parameter_name == "shape2"]

     shape1_outbreak <- param_df$parameter_value[param_df$variable_description == "PPV among suspected cases (chi_epidemic): High estimate (during outbreaks)" & param_df$parameter_name == "shape1"]
     shape2_outbreak <- param_df$parameter_value[param_df$variable_description == "PPV among suspected cases (chi_epidemic): High estimate (during outbreaks)" & param_df$parameter_name == "shape2"]

     # Low estimate (all settings)
     samps_all <- rbeta(5000, shape1 = shape1_all, shape2 = shape2_all)
     ci_all <- quantile(samps_all, probs = c(0.025, 0.5, 0.975))

     df_all <- data.frame(x = samps_all)
     x_vals_all <- seq(0, 1, length.out = 5000)
     y_vals_all <- dbeta(x_vals_all, shape1_all, shape2_all)
     df_beta_all <- data.frame(x = x_vals_all, y = y_vals_all)

     txt_low <- "chi_endemic: All settings"
     p1 <- ggplot(df_all, aes(x = x)) +
          geom_histogram(aes(y = ..density..), bins = 50, fill = "#3498db", color = 'white', alpha = 0.5) +
          geom_line(data = df_beta_all, aes(x = x, y = y), color = "black", linewidth = 1) +
          geom_vline(xintercept = ci_all[c(1,3)], linetype = "dashed", color = "grey20", linewidth = 0.25) +
          geom_vline(xintercept = ci_all[2], linetype = "solid", color = "grey20", linewidth = 0.5) +
          labs(title = "A", y = "Density", x = "") +
          scale_x_continuous(limits = c(0, 1.3), breaks = seq(0, 1, 0.25), expand = c(0, 0)) +
          scale_y_continuous(expand = c(0.005, 0.005)) +
          theme_minimal(base_size = 12) +
          theme(
               legend.position = "none",
               panel.grid.major.y = element_blank(),
               panel.grid.major.x = element_line(color = 'grey80', linewidth = 0.25),
               panel.grid.minor = element_blank(),
               axis.title.x = element_text(margin = margin(t = 25)),
               axis.title.y = element_text(margin = margin(r = 25)),
               plot.margin = unit(c(0.25, 0.25, 0, 0), "inches")
          ) +
          annotation_custom(
               grob = grid::textGrob(stringr::str_wrap(txt_low, 15), gp = grid::gpar(col = "#3498db", fontsize = 10)),
               xmin = 1.2, xmax = 1.2, ymin = 1.5, ymax = 1.5
          )

     # High estimate (during outbreaks)
     samps_outbreak <- rbeta(5000, shape1 = shape1_outbreak, shape2 = shape2_outbreak)
     ci_outbreak <- quantile(samps_outbreak, probs = c(0.025, 0.5, 0.975))

     df_outbreak <- data.frame(x = samps_outbreak)
     x_vals_outbreak <- seq(0, 1, length.out = 5000)
     y_vals_outbreak <- dbeta(x_vals_outbreak, shape1_outbreak, shape2_outbreak)
     df_beta_outbreak <- data.frame(x = x_vals_outbreak, y = y_vals_outbreak)

     txt_high <- "chi_epidemic: During outbreaks"
     p2 <- ggplot(df_outbreak, aes(x = x)) +
          geom_histogram(aes(y = ..density..), bins = 50, fill = "#c0392b", color = 'white', alpha = 0.5) +
          geom_line(data = df_beta_outbreak, aes(x = x, y = y), color = "black", linewidth = 1) +
          geom_vline(xintercept = ci_outbreak[c(1,3)], linetype = "dashed", color = "grey20", linewidth = 0.25) +
          geom_vline(xintercept = ci_outbreak[2], linetype = "solid", color = "grey20", linewidth = 0.5) +
          labs(title = "B", y = "Density", x = expression("PPV among suspected cases (" * chi * ")")) +
          scale_x_continuous(limits = c(0, 1.3), breaks = seq(0, 1, 0.25), expand = c(0, 0)) +
          scale_y_continuous(expand = c(0.005, 0.005)) +
          theme_minimal(base_size = 12) +
          theme(
               legend.position = "none",
               panel.grid.major.y = element_blank(),
               panel.grid.major.x = element_line(color = 'grey80', linewidth = 0.25),
               panel.grid.minor = element_blank(),
               axis.title.x = element_text(margin = margin(t = 25), hjust = -0.1),
               axis.title.y = element_text(margin = margin(r = 25)),
               plot.margin = unit(c(0, 0.25, 0.25, 0), "inches")
          ) +
          annotation_custom(
               grob = grid::textGrob(stringr::str_wrap(txt_high, 18), gp = grid::gpar(col = "#c0392b", fontsize = 10)),
               xmin = 1.2, xmax = 1.2, ymin = 1.5, ymax = 1.5
          )

     # Combine the plots using cowplot
     combo <- cowplot::plot_grid(p1, p2, ncol = 1, align = 'vh')
     print(combo)

     # Save the plot
     plot_path <- file.path(PATHS$DOCS_FIGURES, "prop_suspected_cases.png")
     ggplot2::ggsave(plot_path, plot = combo, width = 10, height = 8, dpi = 300)
     message(paste("Plot saved to:", plot_path))

}
